name: Generate zip file
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build # Remove or modify this step as needed
      run: |
        cd ${{ github.workspace }}/themes/caci
        npm install grunt-cli
        npm install
        ./node_modules/.bin/grunt build

    - uses: actions/upload-artifact@v1
      with:
        name: theme
        path: |
          themes/caci
          !themes/caci/.node-modules